version: '3.10'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 24G
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONMALLOC=malloc
      - MALLOC_TRIM_THRESHOLD_=100000

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  default:
    name: surreal-engine